<a href="https://colab.research.google.com/github/pratyushsingh9870-arch/ML_lab/blob/main/lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================
# 🔹 IMPORT LIBRARIES
# ============================
import numpy as np
import pandas as pd

# ============================
# 🔹 EXPERIMENT 1
# ============================
print("\n===== EXPERIMENT 1 =====")
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)


# ============================
# 🔹 EXPERIMENT 2
# ============================
print("\n===== EXPERIMENT 2 =====")
zeros_matrix = np.zeros((3,4))
ones_matrix = np.ones((2,5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)


# ============================
# 🔹 EXPERIMENT 3
# ============================
print("\n===== EXPERIMENT 3 =====")
arr = np.arange(1, 13)

reshaped = arr.reshape(3,4)

print("Original Array:\n", arr)
print("Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped)
print("Shape:", reshaped.shape)


# ============================
# 🔹 EXPERIMENT 4
# ============================
print("\n===== EXPERIMENT 4 =====")
arr = np.random.randint(1, 100, 10)

print("Array:", arr)
print("Min:", arr.min())
print("Max:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())


# ============================
# 🔹 EXPERIMENT 5
# ============================
print("\n===== EXPERIMENT 5 =====")
data = {
    "Name": ["Aman", "Rahul", "Priya", "Neha"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print(df)
print("\nData Types:\n", df.dtypes)


# ============================
# 🔹 EXPERIMENT 6
# ============================
print("\n===== EXPERIMENT 6 =====")

# Creating sample CSV (auto)
df.to_csv("students.csv", index=False)

df_csv = pd.read_csv("students.csv")

print("First 5 rows:\n", df_csv.head())
print("\nLast 5 rows:\n", df_csv.tail())


# ============================
# 🔹 EXPERIMENT 7
# ============================
print("\n===== EXPERIMENT 7 =====")

print(df_csv.info())

print("\nShape (rows, columns):", df_csv.shape)
print("Missing Values:\n", df_csv.isnull().sum())


# ============================
# 🔹 EXPERIMENT 8
# ============================
print("\n===== EXPERIMENT 8 =====")

print(df_csv.describe())


===== EXPERIMENT 1 =====
Array: [1 2 3 4 5]
Shape: (5,)
Data Type: int64

===== EXPERIMENT 2 =====
Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)

===== EXPERIMENT 3 =====
Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

===== EXPERIMENT 4 =====
Array: [68 32 89 80 87 81 52 84 72 93]
Min: 32
Max: 93
Mean: 73.8
Sum: 738

===== EXPERIMENT 5 =====
    Name  Marks
0   Aman     85
1  Rahul     90
2  Priya     78
3   Neha     92

Data Types:
 Name     object
Marks     int64
dtype: object

===== EXPERIMENT 6 =====
First 5 rows:
     Name  Marks
0   Aman     85
1  Rahul     90
2  Priya     78
3   Neha     92

Last 5 rows:
     Name  Marks
0   Aman     85
1  Rahul     90
2  Priya     78
3   Neha     92

===== EXPERIMENT 7 =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data colum